//this file is generated by OCAnnotation at 2017-07-31 18:26:00 +0800

#ifndef AnnotationDemoAnnotationConfig_gen_h
#define AnnotationDemoAnnotationConfig_gen_h

#define kAnnotationDemoAnnotationConfigs @{\
@"/Users/shiweiran/repo_opensource/OCAnnotation/AnnotationDemo/AnnotationDemo/ViewController.m":@[\
@{\
	@"className":@"ViewController",\
	@"position":@"method",\
	@"type":@"remoteLog",\
	@"methodSelector":@"buttonClicked:",\
	@"params":@{\
		@"type":@"remoteLog",\
		@"remoteLogId":@"userInfo013",\
	},\
},\
],\
}
#endif 
