source "https://rubygems.org" do
  # Gems here
  # gem "bundler", "~> 1.15"
  # gem "rake", "~> 10.0"
  # gem "xcodeproj"
  # gem "psych"
  # gem "activesupport"
  # gem "colored"
  # gem "json"
  # gem "fileutils"
end

